version: '2.1'

services:
  chainpoint-ntpd:
    image: gcr.io/chainpoint-registry/github-chainpoint-chainpoint-ntpd:6247fa638c425ea21582be431a0d7b5cccd73ab7
    container_name: chainpoint-ntpd
    hostname: ntpd
    restart: always
    cap_add:
      - SYS_TIME
      - SYS_NICE
    mem_limit: 64M
