version: '2.1'

services:
  chainpoint-ntpd:
    image: quay.io/chainpoint/chainpoint-ntpd:latest
    container_name: chainpoint-ntpd
    hostname: ntpd
    restart: always
    cap_add:
      - SYS_TIME
      - SYS_NICE
    mem_limit: 64M
